### ISSUE TITLE
default dataaccess.startup.timeoutins = 10800 is too short, could you please change it to larger like 65536?

### ISSUE THREAD

**Issue by StudyExchange** [ambiverse-nlu/ambiverse-nlu#15]
Env: AWS t3a.2xlarge(8CPU 32G)
default dataaccess.startup.timeoutins = 10800 is too short, could you please change it to larger like 65536?

**Comment by hoffart** [comment]
You can overwrite the defaults yourself, see here: https://github.com/ambiverse-nlu/ambiverse-nlu#configuring-the-environment

**Comment by StudyExchange** [comment]
1. I clone the source code
2. set `dataaccess.startup.timeoutins = 108000` at file `./src/main/config/default/aida.properties`
3. run command `export AIDA_CONF=default`
4. run command `docker-compose -f docker-compose/service-postgres.yml up`

but wait seconds do not change, show as below:
`nlu_1  | 2019-12-02 07:29:29,054 [main] INFO  nlu.entitylinking.EntityLinkingManager:206  - Postgres DB seems unavailable. This is expected during first startup using Docker. Waiting for 60s in addition (already waited 1440s, will wait up to 10800s in total)`

How can I change the default 10800s to larger?

**Comment by StudyExchange** [comment]
1. Do not work!
`export AIDA_CONF=aida_20180120_cs_de_en_es_ru_zh_v18_db` seems only change the config folder in the docker image, If change it to small one `aida_20180120_b3_de_en_v18_db` , it's not my purpose. I want to run the full data version.
2. I tried to run [Alternative Ways to Run](https://github.com/ambiverse-nlu/ambiverse-nlu#Alternative-Ways-to-Run). But fialed!
- run 
`export AIDA_CONF=aida_20180120_cs_de_en_es_ru_zh_v18_db`
`./scripts/start_webservice.sh` 
got 
`2019-12-03 13:11:42,642 [main] INFO  nlu.entitylinking.EntityLinkingManager:206  - Postgres DB seems unavailable. This is expected during first startup using Docker. Waiting for 60s in addition (already waited 1020s, will wait up to 108000s in total).`
- run 
`docker run -d --name nlu-db-postgres \`
  `-p 5432:5432 \`
  `-e POSTGRES_DB=aida_20180120_cs_de_en_es_ru_zh_v18_db \`
  `-e POSTGRES_USER=ambiversenlu \`
  `-e POSTGRES_PASSWORD=ambiversenlu \`
  `ambiverse/nlu-db-postgres`
got
`[root@ip-172-31-9-50 ambiverse-nlu]# docker run -d --name nlu-db-postgres \`
`>   -p 5432:5432 \`
`>   -e POSTGRES_DB=aida_20180120_cs_de_en_es_ru_zh_v18 \`
`>   -e POSTGRES_USER=ambiversenlu \`
`>   -e POSTGRES_PASSWORD=ambiversenlu \`
`>   ambiverse/nlu-db-postgres`
`Unable to find image 'ambiverse/nlu-db-postgres:latest' locally`
`latest: Pulling from ambiverse/nlu-db-postgres`
`802b00ed6f79: Pull complete `
`4e0de21e2180: Pull complete `
`58b06ac4cd84: Pull complete `
`14e76b354b47: Pull complete `
`0f0c9f244b65: Pull complete `
`37117d8abb6d: Pull complete `
`8b541f5d818a: Pull complete `
`7cb4855fcd96: Pull complete `
`0a8e3abed67c: Pull complete `
`7fb118f116b6: Pull complete `
`72c7a52fd8b9: Pull complete `
`6118012bd21e: Pull complete `
`35c5098cfeee: Pull complete `
`52e041bc0dfb: Pull complete `
`93b9f4e5f8a2: Pull complete `
`2efb31890df6: Pull complete `
`c32c52d142f0: Pull complete `
`Digest: sha256:695961eff8516186b2946ada2a4d85d28f0ed67c028038dac139c3ddbe60b4b0`
`Status: Downloaded newer image for ambiverse/nlu-db-postgres:latest`
`80d546c7498ed6b0b9ea85e7fddc6ba98a1f49b851082432e344c95060057200`

`nlu-db-postgres` is downloading data at backend?  
`./scripts/start_webservice.sh`  just keep waiting here.
How can make is runable?

**Comment by StudyExchange** [comment]
Make `dataaccess.startup.timeoutins` to be a larger value applying to command `docker-compose -f docker-compose/service-postgres.yml up`, this maybe a easier way to run `aida_20180120_cs_de_en_es_ru_zh_v18_db`?
Anyone else can run this project? and how do you run it?
I stuck here!

**Comment by StudyExchange** [comment]
Success! Thank you very much!
Reference: https://github.com/ambiverse-nlu/dockerfiles/issues/5
