### ISSUE TITLE
Cannot run docker container

### ISSUE THREAD

**Issue by exelents** [ambiverse-nlu/ambiverse-nlu#24]
Hi. I'm trying to run a full-sized docker container, as in quick start guide, but i got a bunch of errors in console. Looks like containers started, and even serving 8080 port, but there are errors in console, and curl request returns nothing. Also, it seems data for database haven't downloaded, and 387 GB disk space is still free.

Here is console output:
https://pastebin.com/XgT56FvB

What can I do?

**Comment by ghost** [comment]
Have you resolved this issue?

**Comment by exelents** [comment]
> Have you resolved this issue?

Yes, I have. Problem seems was I interrupted creating container before, and some packages haven't installed, or database haven't populated, or something like that. Deleting containers and images, and recreating container have solved the problem.

Now I use a database installed without container, and run app via scripts/start_webservice.sh , and seems everything works fine.
