### ISSUE TITLE
AmbiverseNLU returning 404 errror after build

### ISSUE THREAD

**Issue by dpancic** [ambiverse-nlu/ambiverse-nlu#3]
After a successful build application returning 404 error:

```
HTTP ERROR 404
Problem accessing /. Reason:

    Not Found
Powered by Jetty:// 9.4.4.v20170414
```

The log file is attached and it does not show errors.

[ambiversenlu.log](https://github.com/ambiverse-nlu/ambiverse-nlu/files/2850231/ambiversenlu.log)

**Comment by dmilcevski** [comment]
How does your service call look like? 
It should be something like this:
~~~~
url --request POST \
  --url http://localhost:8080/entitylinking/analyze \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --data '{"docId": "doc1", "text": "Jack founded Alibaba with investments from SoftBank and Goldman.", "extractConcepts": "true" }'
~~~~

There is nothign on `localhost:8080` if this is what you are trying to access. The valid path is `http://localhost:8080/entitylinking/analyze`

**Comment by dpancic** [comment]
Thank you,

It works from the command line but I thought that in addition to that application also has a web interface like one that is shown on the demo page https://ambiversenlu.mpi-inf.mpg.de/

Does this application have only a command line interface?

**Comment by dmilcevski** [comment]
The system has two ways to run. Command Line described [here](https://github.com/ambiverse-nlu/ambiverse-nlu#run-a-pipeline-from-the-command-line) and with a webservice call, described [here](https://github.com/ambiverse-nlu/ambiverse-nlu#call-the-web-service-using-docker). The one that you are referring is a webservice call. The interface shown on the demo page is available in another [repository](https://github.com/ambiverse-nlu/ambiversenlu-demo-wp-plugin) as a wordpress plugin. This plugin for now connects to the public API of our web service. If you want to use it, you probably have to change the source code to connect to your service.
