### ISSUE TITLE
 4-5 hours to process a single request

### ISSUE THREAD

**Issue by vandit009** [ambiverse-nlu/ambiverse-nlu#32]
We have set up the full Postgres database and jetty on the server which has 32 GB of RAM and 512 Hard disk space.  
When we request to URL localhost:8080/factextraction/analyze, It usually takes around 4-5 hours to process a single request. I am not sure why It is taking so long?  
I also tried the pipeline which is better than a URL. but still takes 2 hours for a document  
In a smaller database, It takes seconds to generate a response.  
In the documentation, It says Ambiverse-nlu only needs 16GB of Main memory to process a single document.  
Can you tell me what is the https://ambiversenlu.mpi-inf.mpg.de/ memory configuration in the demo site or what is the ideal configuration we should keep on the server?  
Is there any way to Improve Performance and how many cores/threads I can use at a time?

**Comment by dmilcevski** [comment]
The `/factextraction` endpoint is not working properly and sometimes returns null pointer exception. Did you try the `/entitylinking` endpoint?
The demo runs with cassandra as database, and the memory configuration is actually pretty high, 80GB. However, you might try with little bit bigger memory than 16GB ram, like 20 or 24GB of ram. I would give at least 4 CPUs to the container.
Postgresql is slower backend for the entitylinking. It also depends how big is your document. 
You can find out what is going on from the logs.

**Comment by vandit009** [comment]
Thank you. I increased the RAM of the server and it is working fine. Now It is taking less than a second for a document.
