### ISSUE TITLE
Coverage/quality of aida_20180120_cs_de_en_es_ru_zh_v18.sql.gz

### ISSUE THREAD

**Issue by hpreki** [ambiverse-nlu/ambiverse-nlu#4]
We installed and (superficially) tested ambiverse using the "small" dataset  (aida_20180120_b3_de_en_v18.sql.gz) but found it lagging far behind  the (impressive) quality of the online-demo. 
We hope, that we  soon will have the necessary resources (RAM) in place to use the "big" dataset (aida_20180120_cs_de_en_es_ru_zh_v18.sql.gz).

But before we get too enthusiastic beforehand (and thus too disappointed afterwards): can anyone comment on what to expect from the big dataset in comparison to the online demo?  Is the "coverage/quality" the same?   
I am talking about performing named entitiy on German and English texts, btw.

**Comment by hoffart** [comment]
Thanks for your interest!

The demo is using the aida_20180120_cs_de_en_es_ru_zh_v18 dataset, you will get the same quality.

The small dataset is really only for playing around and making sure that things work.
