### ISSUE TITLE
ERROR:  relation "word_ids" does not exist

### ISSUE THREAD

**Issue by GamalC** [ambiverse-nlu/ambiverse-nlu#8]
Thanks for building and open sourcing this really impressive looking tool.
I am trying to set it up locally using the large database and have followed the instructions in the READMe, however I am having the above error on startup. Any assistance in solving it would be great.

More comprehensive error message:

`ERROR:  relation "word_ids" does not exist at character 22
STATEMENT:  SELECT word, id FROM word_ids WHERE word IN (E'Messi',E'juega',E'al',E'futbol',E'en',E'Barcelona',E'.',E'Maradona',E'tambien',E'jugo',E'en',E'Barcelona',E'y',E'luego',E'fue',E'al',E'Napoli',E'.')
de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.access.EntityLinkingDataAccessException: org.postgresql.util.PSQLException: ERROR: relation "word_ids" does not exist`

**Comment by hoffart** [comment]
Did you make sure to import the database dumps? The Docker images (https://github.com/ambiverse-nlu/ambiverse-nlu#start-the-database-backend) should actually be doing this automatically. How did you start Postgres?

**Comment by GamalC** [comment]
Hi @hoffart, thanks for replying. I cloned the repo and used the docker-compose command under the Quickstart section of the READMe. I expected that the Docker images would import the database dumps. When I run with docker-compose, I get an error similar to Issue #5 and it ultimately times out.  

I have also tried starting the database by itself using the commands under 'Alternative Ways to Run'. I need to make the changes explained in Issue #5 by @malteos to get the small database to work, but when I try querying that server, the response I get is 
`"message": "Please provide language on input."`

Doing the commands under 'Alternative Ways to Run' with the large database gives me the error above.

**Comment by hoffart** [comment]
You are very close! Just add 
`"language": "en"`
to your input, for example:
```
curl --request POST \
  --url http://localhost:8080/factextraction/analyze \
  --header 'accept: application/json' \
  --header 'content-type: application/json' \
  --data '{"docId": "doc1", "text": "Jack founded Alibaba with investments from SoftBank and Goldman.", "extractConcepts": "true", "language": "en" }'
```
The message simply means that the automatic language detection failed, for example because the input text was too short.

**Comment by GamalC** [comment]
Hi @hoffart, thanks for the response. I had tried solving that issue by adding the Content-Language to the HTTP header with curl, which didn't work. When I tried what you suggested, it worked. Thanks!

I am now however in the same position as @timrepke in Issue #5: when I do the exact same settings for the full database, I get the `Postgres DB seems unavailable` error, which is mystifying as the database is there, there is enough memory (>45GB) and the only difference is the use of the larger database. 
I also still get the original error when I run directly with the docker-compose. It's great that it now works with the small database, but as is mentioned on the page, that database is not as useful as the full one (in the example case for instance, it only links a single entity: Goldman Sachs).

**Comment by hoffart** [comment]
How long did you wait for the full db to come up? It is importing a very large file, which can take a couple of hours.

**Comment by GamalC** [comment]
Hi @hoffart, thanks for responding. 

Yes I realised later that the full database takes quite a while to become available (about 2 hours on my machine). When I took that into consideration and run the script after I am able to connect to the database, the server comes up but I now get an error and there is no response from calls to the server.

The core error message seems to be `Caused by: de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.processor.UnprocessableDocumentException: de.mpg.mpi_inf.ambiversenlu.nlu.entitylinking.access.EntityLinkingDataAccessException: java.lang.NullPointerException`.

**Comment by GamalC** [comment]
Update:
It seems the trigger for this error is line 98 in the DocumentProcessor.java file:
`AnalysisEngine ae = PipelinesHolder.getAnalyisEngine(type);`
 `ae.process(jcas);`

**Comment by hoffart** [comment]
Thanks for getting back to us with this. Can you please provide the call that you are doing so that we can reproduce? curl syntax is preferred.

**Comment by GamalC** [comment]
Hi @hoffart, thanks for responding. 
I am not making a call to the server as it is not coming up. The error is thrown when I run the `./scripts/start_webservice.sh` command to get the server up after the large database is available. Note that the small database works fine, so it would seem that the problem lies with something that is done differently for the large database.

**Comment by GamalC** [comment]
Update from further investigations:
The error more specifically comes from Line 187 in DataAccessSQL.java: `entities.add(new Entity(yagoEntityIds.get(ids[i]), ids[i]));`
The call `yagoEntityIds.get(ids[i])` returns null which possibly raises the NullPointer error.

I will look more into that call, but any help on elucidating why this call may return null would be helpful.

**Comment by hoffart** [comment]
This sounds like the database is incomplete - every id that is passed there should be present. I would first try to reimport the database and make sure to wait until it is fully populated.
I cannot more than guess unfortunately, I have never seen this concrete error.

**Comment by GamalC** [comment]
Hi @hoffart, yes I realised after further investigations since the last post that only 5 tables in the database were populated. The database does not seem to become more populated as time goes on though; it seemed to have the same amount of data 3 days later as it did 2 hours after running the docker command. I am not sure why it stops populating. I will investigate other means of getting the full database loaded and report back.
Thanks for all your help on this!

**Comment by GamalC** [comment]
Hi @hoffart, I can't seem to find the disk space requirements for the full database in the repo (https://github.com/ambiverse-nlu/ambiverse-nlu#resource-considerations). You mentioned 100 GB on another Issue, but my latest attempt used up 174 GB but only loaded 12 tables. The dump (http://ambiversenlu-download.mpi-inf.mpg.de/) seems to be 25 GB. 
Do you know how much disk space is required for the full database to load?

**Comment by GamalC** [comment]
I can now report that I am able to get Ambiverse running with the full database! Although I get a few warnings when the server starts, it returns results for the test sentence.  
It seems that all my issues were in fact database related. The full database required 358GB and 9 hours to fully populate on my machine. It would be good if that is perhaps added to the Resource Considerations section of the READMe since some users may find that information useful. I can add it if that is preferable.
 
As the READMe mentions, the database_aida.properties also had to be modified, although it does not give any further details. In the end the following config worked for me:
`dataSourceClassName = org.postgresql.ds.PGSimpleDataSource`
`dataSource.serverName = localhost`
`dataSource.databaseName = aida_20180120_cs_de_en_es_ru_zh_v18`
`dataSource.portNumber = 5432`
`dataSource.user = ambiversenlu`
`dataSource.password = ambiversenlu`
`maximumPoolSize = 5`
  
Thanks again for making such a great resource available and thanks for all the help on this issue  @hoffart.

**Comment by hoffart** [comment]
Glad this worked out for you now! We added a section on the disk space requirements (387 according to pgAdmin stats), thanks for pointing this one out.

**Comment by PanagiotisDrakatos** [comment]
@GamalC  i am facing the same issue take a look here https://github.com/ambiverse-nlu/ambiverse-nlu/issues/34#issuecomment-749544536 can y help me to figure it out?
